name: CI
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  linuxbuild:
    runs-on: ubuntu-latest
    steps:
      - run: .github/build.bash linux
  winbuild:
    runs-on: windows-2019
    steps:
      - run: .github/build.bash windows
  macbuild:
    runs-on: macos-11
    steps:    
      - run: .github/build.bash osx
