name: Release CI
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  linuxbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - run: .github/build.bash linux
        id: build
        shell: bash
      - name: Release 
        uses: xresloader/upload-to-github-release@v1.3.2
        with:
          file: target/*.deb;target/*.rpm
          tags: true
  winbuild:
    runs-on: windows-2019
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - run: .github/build.bash windows
        id: build
        shell: bash
      - name: Release 
        uses: xresloader/upload-to-github-release@v1.3.2
        with:
          file: target/*.msi
          tags: true
  macbuild:
    runs-on: macos-11
    steps:    
      - name: Checkout master
        uses: actions/checkout@v2
      - run: .github/build.bash osx
        id: build
        shell: bash
      - name: Release 
        uses: xresloader/upload-to-github-release@v1.3.2
        with:
          file: target/*.dmg
          tags: true
